# Generated by Django 5.0.3 on 2024-06-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_cart_quantity_orders_delete_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Products',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Products',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='User',
            new_name='user',
        ),
    ]
